config/routes.rb
Rails.application.routes.draw do
  get 'inquiries/new'
  get 'inquiries/create'
  root 'homes#top'

  resources :inquiries, only:[:new, :create]
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
   devise_scope :user do
    # get '/users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    # # post '/users/sign_in' => 'users/sessions#create', as: 'user_session'
    # delete '/users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    # get '/users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    get '/users/passwords/edit' => 'users/registrations#edit', as: 'password_edit_registrations'
    patch '/users/passwords/update' => 'users/registrations#update'
    # post 'users/sign_up' => 'users/registrations#create', as: 'user_registration'
    # get '/users/' => 'users/passwords#edit', as: 'edit_user_password'
    # patch '/users/passwords' => 'users/passwords#update', as: 'user_password'
    get '/users/passwords/new' => 'users/passwords#new',as: 'user_forgot_password'
   end

  namespace :users do
    get 'users/select' => 'user_favorites#select', as: 'select_user_favorite'
    get 'users/new/:id' => 'user_favorites#new', as: 'new_user_favorite'
    resources :user_favorites, only:[:create, :show, :edit, :update, :destroy, :index]
    get 'users/genre_index' => 'pastes#genre_index', as: 'genre_index_paste'
    resources :pastes
  end
  # resources :pastes do
  #   resources :user_favorites
  # end


  devise_for :admins, skip: :all
    devise_scope :admin do
      get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
      post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
      delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session' 
    end
  authenticated :admin do
    namespace :admins do
      resources :genres, only:[:index, :create, :destroy, :edit, :update]
      get 'download',to:'pastes#download', as: 'download'
      resources :pastes, only:[:new, :create, :edit, :update, :destroy] do
         collection { post :import }
        # collection { post :csv_import }
      end
      resources :admin_recommends, only:[:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/admin_recommend.rb
class AdminRecommend < ApplicationRecord
    belongs_to :admin
    belongs_to :paste
    validates :comment, presence: true
    validates :paste_id, uniqueness: true
end

app/controllers/admins/admin_recommends_controller.rb
class Admins::AdminRecommendsController < ApplicationController
    def new
        @genres = Genre.all
        @recommend = AdminRecommend.new
        @q = Paste.ransack(params[:q])
        @pastes = {}
        if params[:q].present?
          @paste = @q.result(distinct: true)
          @pastes = @paste.page(params[:page]).reverse_order.per(5)
        end
        # ↓ターミナルのログで、入ってるデータを確認することができる
        # logger.debug 'zzzzzzzz'　　　　　　　　　　　　 ←ログで見つけやすいように適当な文字打ってあるだけなのでなくてもok
        # logger.debug current_admin.inspect　　　　　　←確認したいインスタンス.inspectで中身のデータ見れる
        # logger.debug 'zzzzzzzzz'
        
    end
    def create
        @recommend = AdminRecommend.new(recommend_params)
        @recommend.admin_id = current_admin.id
        if @recommend.save
            flash[:notice] = "お気に入りを登録しました"
            redirect_to admins_admin_recommends_path
        else
            @genres = Genre.all
            @q = Paste.ransack(params[:q])
            @pastes = {}
            if params[:q].present?
              @paste = @q.result(distinct: true)
              @pastes = @paste.page(params[:page]).reverse_order.per(5)
            end
            flash.now[:notice] = "登録に失敗しました、内容を確認して下さい<br>・コメント内容が空ではないですか？<br>・既にお気に入り登録した製品ではないですか?".html_safe
            render :new
        end
             
    end
    def edit
        @recommend = AdminRecommend.find(params[:id])        
    end
    def update
        @recommend = AdminRecommend.find(params[:id])
		if @recommend.update(recommend_params)
			flash[:notice] = "コメントを編集しました"
			redirect_to action: :index
		else
			flash.now[:notice] = "コメント編集に失敗しました。入力を確認してください。<br>・コメント記入欄が空ではないですか?".html_safe
			render :edit
		end
    end
    def destroy
        @recommend = AdminRecommend.find(params[:id])
        if  @recommend.destroy
            flash[:notice] = "お気に入りを削除しました"
            redirect_back(fallback_location: admins_genres_path)
        else
            flash[:notice] = "削除出来ませんでした"
            redirect_back(fallback_location: root_path)
        end
    end
    def index
        @recommends = AdminRecommend.page(params[:page]).reverse_order
    end
    private
	def recommend_params
        params.require(:admin_recommend).permit(:paste_id, :comment, :admin_id)
    end
end

app/helpers/admins/admin_recommends_helper.rb
module Admins::AdminRecommendsHelper
end

app/views/admins/admin_recommends/edit.html.erb
<div class="container" style="margin:0 50px 0;">
    <div class="row">
        <div class="col-12 text-left">
                <%= flash[:notice] %>
        </div>
    </div>
    <div class="row">
        <div class="col-3 text-center">
            <h5 class="bg-info text-white rounded p-1 mt-3 mb-5">おすすめ編集</h5>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-3">
            <%= attachment_image_tag(@recommend.paste, :image, size: '150x150') %>
        </div>
        <div class="col-9 row">
            <div class="col-3"><%= @recommend.paste.genre.genre_name %></div>
            <div class="col-7"><%= @recommend.paste.tooth_paste_name %></div>
            <div class="col-2"><%= @recommend.paste.price %>円</div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 m-3">
            <%= form_for(@recommend,url:admins_admin_recommend_path(@recommend), method: :patch, local:true) do |f| %>
            <%= f.label :comment, "コメント編集" %>
            <%= f.text_area :comment, class:"form-control", style:"width: 90%; height:150px; " %>
        </div>
        <div class="col center-auto my-2">
            <%= f.submit "変更を保存する", class: "btn-primary ml-5",style:"border-radius: 0.3em" %>
            <% end %>
        </div>
    </div>
</div>

app/views/admins/admin_recommends/index.html.erb
<div class="main-box">
  <div class="container" style="margin:0 50px 0;">
      <div class="row">
          <div class="col-6 text-left mb-3">
                  <%= flash[:notice] %>
          </div>
      </div>
      <div class="row">
          <div class="col-3 text-center">
              <h5 class="bg-info text-white rounded p-1 mb-5">おすすめ一覧</h5>
          </div>
      </div>
  </div>

  <div class="container">
    <% @recommends.each do |recommend| %>
      <div class="row mt-4">
        <div class="col-2"><%= attachment_image_tag(recommend.paste, :image, size: '150x150') %></div>
        <div class="col-8 row">
          <div class="col-3">ジャンル:<%= recommend.paste.genre.genre_name %></div>
          <div class="col-6">製品名:<%= recommend.paste.tooth_paste_name %></div>
          <div class="col-3">値段:<%= recommend.paste.price %>円</div>
          <div class="col-12">コメント:<%= recommend.comment %></div>
        </div>
        <div class="col-2 row">
          <div class="col-6"><%= link_to "編集", edit_admins_admin_recommend_path(recommend), class:"btn btn-primary" %></div>
          <div class="col-6"><%= link_to "削除", admins_admin_recommend_path(recommend), method: :delete, data: { confirm: "削除しますか？" },
          class:"btn btn-danger" %></div>
        </div>
      </div>
    <% end %>
    <%= paginate @recommends %>
  </div>
</div>

app/views/admins/admin_recommends/new.html.erb
<div class="main-box">
  <div class="container" style="margin:0 50px 0;">
      <div class="row">
          <div class="col-6 text-left mb-2">
                  <%= flash[:notice] %>
          </div>
      </div>
      <div class="row">
          <div class="col-3 text-center">
              <h5 class="bg-info text-white rounded p-1 mb-4">おすすめ新規登録</h5>
          </div>
      </div>
  </div>

<%# genre_genre_name_eq → モデル名_カラム名_eq（ransackの書き方） %>
  <div class="container">
    <%= search_form_for(@q,url:new_admins_admin_recommend_path, method: :get, local:true) do |f| %>
      <div class="row">
        <div class="col-2"><%= f.label :genre_genre_name, "ジャンル名" %><br>
          <%= f.collection_select :genre_genre_name_eq, @genres, :genre_name, :genre_name, {}, {class: 'form-control'} %>
        </div>
        <div class="col-3"><%= f.label :tooth_paste_name, "Keyword" %><br>
          <%= f.search_field :tooth_paste_name_cont, class:"form-control" %>
        </div>
        <div class="col-5"> <%= f.label :price %><br>
          <%= f.number_field :price_gteq %>以上〜
          <%= f.number_field :price_lt %>未満
        </div>
        <div class="col-2 text-left"><br><%= f.submit "検索" %></div>
      </div>
    <% end %>
  </div> 

  <div class="container">
    <% @pastes.each do |paste| %>
      <div class="row my-3">
        <div class="col-2"><%= attachment_image_tag(paste, :image, size: '150x150') %></div>
        <div class="col-10 row">
          <div class="col-3"><%= paste.genre.genre_name %></div>
          <div class="col-6"><%= paste.tooth_paste_name %></div>
          <div class="col-2"><%= paste.price %>円<br></div>
          <div class="col-10">
            <%= form_for(@recommend, url:admins_admin_recommends_path, method: :post) do |f| %>
            <%= f.label :comment %>
            <%= f.text_area :comment, class:"form-control", placeholder:"コメントをここに書いてください" %>
            <%= f.hidden_field :paste_id, :value => paste.id %></div>
          <div class="col-2"><br><br><%= f.submit "登録する" %><% end %></div>
        </div>
      </div>
    <% end %>
    <% if @pastes.present? %>
      <%= paginate @pastes %>
    <% end %>
  </div>
</div>