config/routes.rb
Rails.application.routes.draw do
  get 'inquiries/new'
  get 'inquiries/create'
  root 'homes#top'

  resources :inquiries, only:[:new, :create]
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
   devise_scope :user do
    # get '/users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    # # post '/users/sign_in' => 'users/sessions#create', as: 'user_session'
    # delete '/users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    # get '/users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    get '/users/passwords/edit' => 'users/registrations#edit', as: 'password_edit_registrations'
    patch '/users/passwords/update' => 'users/registrations#update'
    # post 'users/sign_up' => 'users/registrations#create', as: 'user_registration'
    # get '/users/' => 'users/passwords#edit', as: 'edit_user_password'
    # patch '/users/passwords' => 'users/passwords#update', as: 'user_password'
    get '/users/passwords/new' => 'users/passwords#new',as: 'user_forgot_password'
   end

  namespace :users do
    get 'users/select' => 'user_favorites#select', as: 'select_user_favorite'
    get 'users/new/:id' => 'user_favorites#new', as: 'new_user_favorite'
    resources :user_favorites, only:[:create, :show, :edit, :update, :destroy, :index]
    get 'users/genre_index' => 'pastes#genre_index', as: 'genre_index_paste'
    resources :pastes
  end
  # resources :pastes do
  #   resources :user_favorites
  # end


  devise_for :admins, skip: :all
    devise_scope :admin do
      get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
      post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
      delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session' 
    end
  authenticated :admin do
    namespace :admins do
      resources :genres, only:[:index, :create, :destroy, :edit, :update]
      get 'download',to:'pastes#download', as: 'download'
      resources :pastes, only:[:new, :create, :edit, :update, :destroy] do
         collection { post :import }
        # collection { post :csv_import }
      end
      resources :admin_recommends, only:[:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_favorites, dependent: :destroy
  has_many :social_profiles, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20] # ランダムなパスワードを作成
    end
  end

end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
    belongs_to :user
    belongs_to :paste
    validates :comment, presence: true, length: { minimum: 2 }
    # validates :paste_id, uniqueness: true
end 

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    # 保存されている時の処理
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end


  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: 'google') if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except('extra')
      #google認証の場合は、なぜかauth_hashの容量が大きく、一瞬で容量オーバーとなるため、新規登録時に必要な情報のみをsessionに渡すこととしました。（おそらく画像データのせい？）
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/pastes_controller.rb
class Users::PastesController < ApplicationController
    def index
      # ↓pasteのランキング
      user_favorites = UserFavorite.joins(:paste).group("tooth_paste_name").order('count_all DESC').count
      @user_favorites = []    #空の配列を定義しておく
      user_favorites.each do |user_favorite|               #image表示させたいので、pasteの情報も欲しいので配列にいれる
        array = [
          user_favorite,
          Paste.find_by(tooth_paste_name: user_favorite[0])
        ]
        @user_favorites.push(array)                   #array=[0,1]で取れる
      end

      # genre別ランキング
      @genres = Genre.all
      @q = Genre.ransack(params[:q])
      @user_favorite_genre = {}
      if params[:q] && params[:q][:genre_name_eq].present?  #検索された場合の処理
        @genre = @q.result(distinct: true)
        user_favorite_genre = UserFavorite.joins(:paste).where('pastes.genre_id = ?', @genre.ids).group("tooth_paste_name").order('count_all DESC').count
        @user_favorite_genre = []   #空の配列を定義しておく
      end
    end
    def genre_index
      @genres = Genre.all
      @q = Genre.ransack(params[:q])
      @user_favorite_genre = {}  #eash文に渡すように空の@pastes定義しておく（エラー対策）
      if params[:q] && params[:q][:genre_name_eq].present?  #検索された場合の処理
        @genre = @q.result(distinct: true)
        user_favorite_genre = UserFavorite.joins(:paste).where('pastes.genre_id = ?', @genre.ids).group("tooth_paste_name").order('count_all DESC').count
        @user_favorite_genre = []   #空の配列を定義しておく
        user_favorite_genre.each do |user_favorite_genre|               #pasteの情報も欲しいので配列にいれる
          array = [
            user_favorite_genre,
            Paste.find_by(tooth_paste_name: user_favorite_genre[0])
          ]
          @user_favorite_genre.push(array)                   #array=[0,1]で取れる
        end
      end
    end
    def show
        @paste = Paste.find(params[:id])
        @user_comments = UserFavorite.where('paste_id = ?', @paste) 
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/user_favorites_controller.rb
class Users::UserFavoritesController < ApplicationController
    def select
      @genres = Genre.all
      @user_favorite = UserFavorite.new
      @q = Paste.ransack(params[:q])
      @pastes = {}  #eash文に渡すように空の@pastes定義しておく（エラー対策）
      if params[:q].present?  #検索された場合の処理
        @paste = @q.result(distinct: true)
        @pastes = @paste.page(params[:page]).reverse_order.per(5)
      end
      @user_id = current_user.id
    end
    def new
      @paste = Paste.find(params[:id])
      @comment = UserFavorite.new
    end
    def create
      comment = UserFavorite.new(user_favorite_params)
      comment.user_id = current_user.id
      if  comment.save
          flash[:success] = 'コメントしました'
          redirect_to users_user_favorite_path(comment.id)
      else
        flash[:notice] = 'コメント欄が空です'
        redirect_back(fallback_location: root_path)
      end
    end
    def show
       @user_favorites = current_user.user_favorites.all.page(params[:page]).reverse_order

    end
    def edit
      # @user_favorite = UserFavorite.where(user_id: current_user.id)
      #  ↑の書き方と↓同じ意味どっちでもokだが、↓の方が文法的にわかりやすいので◎
      @user_favorite = current_user.user_favorites.find(params[:id])
    end
    def update
      @user_favorite = current_user.user_favorites.find(params[:id])
      if  @user_favorite.update(user_favorite_params)
          flash[:success] = '更新しました'
          redirect_to users_user_favorite_path(:id)
      else
        flash[:notice] = "変更に失敗しました。もう一度変更し直して下さい<br>・コメント内容が空では無いですか？"
        redirect_back(fallback_location: root_path)
      end
    end
    def destroy
      @user_favorite = current_user.user_favorites.find(params[:id])
      if  @user_favorite.destroy
          flash[:success] = "お気に入りを削除しました"
          redirect_to users_user_favorite_path(:id)
      else
          flash[:notice] = '削除に失敗しました'
          redirect_back(fallback_location: root_path)
      end
    end
    def index
      # pasteの総合ランキング
      user_favorites = UserFavorite.joins(:paste).group("tooth_paste_name").order('count_all DESC').count
      @user_favorites = []    #空の配列を定義しておく
      user_favorites.each do |user_favorite|               #image表示させたいので、pasteの情報も欲しいので配列にいれる
        array = [
          user_favorite,
          Paste.find_by(tooth_paste_name: user_favorite[0])
        ]
        @user_favorites.push(array)                   #array=[0,1]で取れる
      end     
       
      @admin_recommends = []
      @admin_recommends = AdminRecommend.page(params[:page]).reverse_order.per(3)

       # genre別ランキング
      @genres = Genre.all
      @q = Genre.ransack(params[:q])
      @user_favorite_genre = {}  #eash文に渡すように空の@pastes定義しておく（エラー対策）
      if params[:q] && params[:q][:genre_name_eq].present?  #検索された場合の処理
        # params[:q]が存在しているかまず検証し、かつparams[:q][:genre_name_eq]が存在しているか検証してる
        # params[:q][:genre_name_eq].present?　だけだとそもそもparams[:q]が存在しない場合[:genre_name_eq]なんてメソッドは存在しないことになるのでエラー吐かれる
        @genre = @q.result(distinct: true)
        user_favorite_genre = UserFavorite.joins(:paste).where('pastes.genre_id = ?', @genre.ids).group("tooth_paste_name").order('count_all DESC').count
        @user_favorite_genre = []   #空の配列を定義しておく
        user_favorite_genre.each do |user_favorite_genre|               #pasteの情報も欲しいので配列にいれる
          array = [
            user_favorite_genre,
            Paste.find_by(tooth_paste_name: user_favorite_genre[0])
          ]
          @user_favorite_genre.push(array)                   #array=[0,1]で取れる
        end

      end
      @user_id = current_user.id
    end
    private
    def user_favorite_params
        params.require(:user_favorite).permit(:comment, :paste_id, :user_id)
    end
end

app/helpers/users/pastes_helper.rb
module Users::PastesHelper
end

app/helpers/users/user_favorites_helper.rb
module Users::UserFavoritesHelper
end

app/views/users/user_favorites/edit.html.erb
<div class="main-visual">
  <div class="main-visual-content">
      <p class="main-visual-text font-color-white">
          <%= current_user.name %>さんの<br>
          お気に入り編集ページ<br>
      </p>
  </div>
</div>

<div class="flash_message">
  <%= sanitize flash[:notice] %>
</div>

  <div class="my_page_box" style="height: 300px;">
    <div class="container">
      <div class="row">
        <div class="col-12 m-3">
            製品名:<%= @user_favorite.paste.tooth_paste_name %>
        </div>
        <div class="col-3 row">
          <div class="col-12">
            <%= attachment_image_tag(@user_favorite.paste, :image, size: '180x180') %>
          </div>
        </div>
        <div class="col-9 row">
          <div class="col-11 offset-1 m-0">
            ジャンル:<%= @user_favorite.paste.genre.genre_name %>
          </div>
          <div class="col-11 offset-1 m-1">
             値段   :<%= @user_favorite.paste.price %>円
          </div>
          <%= form_for(@user_favorite,url:users_user_favorite_path(@user_favorite), method: :patch) do |f| %>
          <div class="col-11 offset-1 m-1">
            <%= f.label :comment, "コメント編集:" %>
            <%= f.text_area :comment, class:"form-control", style:"width: 700px;" %>
          </div>
          <div class="col-11 offset-1 m-2">
              <%= f.submit "変更を保存する", class:"btn-flat-border" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
 </div>

app/views/users/user_favorites/index.html.erb
<div class="main-visual">
    <div class="main-visual-content">
        <p class="main-visual-text font-color-white">
            toothpaste<br>
            user ranking<br>
            admin ranking
        </p>
    </div>
</div>
<div class="wrapper clearfix">
    <main class="main">
        <section>
            <h1>総合ランキング</h1>
            <h2><%= link_to "総合ランキングを全部見る", users_pastes_path, class:"font-color" %></h2>
                <div class="index_container">
                    <% @user_favorites.each_with_index do |favorite, i| %>
                        <% if i < 3 %>
                            <div class="index_box">
                                <i class="fas fa-crown"></i>
                                <%= i + 1 %>位<br>
                                <%= attachment_image_tag(favorite[1], :image, size: '200x200') %><br>
                                <%= favorite[1].genre.genre_name %><br>
                                <%= favorite[0].first %><br>
                                <i class="far fa-comment-dots"></i>
                                <%= favorite[0].second %><br>
                                <%= link_to "詳しく見る", users_paste_path(favorite[1].id), class:"font-color" %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
        </section>
        <section>
        <%= search_form_for(@q,url:users_user_favorites_path, method: :get, local:true) do |f| %>
            <ul>
                <li>
                    <%= f.label :genre_name, "ジャンル別ランキング", class:"font-color-white" %>
                </li>
                <li>
                    <%= link_to "ジャンル別ランキングを全部見る", users_genre_index_paste_path, class:"font-color" %>
                </li>
                <div class="select_box">
                    <%= f.collection_select :genre_name_eq, @genres, :genre_name, :genre_name,{prompt: ""}, {class: 'form-control ransack-textbox-index'} %>
                </div>
                <li>
                    <%= f.submit "Search", class:"btn-flat-border" %>
                </li>
            </ul>
            <% if  @genre.present? %>
                ジャンル:<%= @genre[0].genre_name %>
            <% end %>
        <% end %>
        <div class="index_container">
            <% @user_favorite_genre.each_with_index do |favorite, i| %>
                <% if i < 3 %>
                    <div class="index_box">
                        <i class="fas fa-crown"></i>
                        <%= i + 1 %>位<br>
                        <%= attachment_image_tag(favorite[1], :image, size: '150x150') %><br>
                        <%= favorite[1].genre.genre_name %><br>
                        <%= favorite[0].first %><br>
                        <i class="far fa-comment-dots"></i>
                        <%= favorite[0].second %><br>
                        <%= link_to "詳しく見る", users_paste_path(favorite[1].id), class:"font-color" %>
                    </div>
                <% end %>
            <% end %>
        </section>
    </main>
    <div class="sidemenu">
        <section class="popular">
            <h4 class="sidebar-headline">運営者のおすすめ</h4>
                <div class="sidebar-contents">
                    <% @admin_recommends.each do |recommend| %>
                    <div class="container">
                        <div class="row">
                            <div class="col-6">
                                <%= attachment_image_tag(recommend.paste, :image, size: '100x100') %></div>
                            <div class="col-6 row">
                                    <%= recommend.paste.genre.genre_name %>
                                <div class="col-12">
                                    <%= recommend.paste.tooth_paste_name %>
                                </div>
                                <div class="col-12">
                                    <%= link_to "詳しく見る", users_paste_path(recommend.paste_id), class:"font-color" %>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="admin_tag">
                                    <%= recommend.comment %>
                                </div>
                            </div>     
                        </div>
                    </div>
                    <% end %>
                    <% if @admin_recommends.present? %>
                        <%= paginate @admin_recommends %>
                    <% end %>
                </div>
        </section>
    </div>
</div>

app/views/users/user_favorites/new.html.erb
userおすすめ歯磨き粉選択後
コメント記入ページ
  <div class="my_page_box">
    <div class="container">
      <div class="row">
        <div class="col-3">
         <%= attachment_image_tag(@paste, :image, size: '180x180') %><br>
        </div>
        <div class="col-9 row">
            <div class="col-11 offset-1">
                ジャンル:<%= @paste.genre.genre_name %>
            </div>   
            <div class="col-11 offset-1">
                製品名：<%= @paste.tooth_paste_name %>
            </div>
            <div class="col-11 offset-1">
                値段<%= @paste.price %>円
            </div>
        </div>
      </div>
    </div>
  </div>
<%# コメント記入用 %>
<div class="container">
  <div style="margin-left:50px;">
    <%= flash[:notice] %>
  </div>
  <%= form_for(@comment, url:users_user_favorites_path) do |f| %>
    <div class="row text-center m-4">
      <div class="col-12">
        <%= f.text_area :comment, class:"form-control",placeholder:"コメントをここに"%>
        <%= f.hidden_field :paste_id, :value => @paste.id %> 
      </div>
    </div>
    <div class="row m-4">
      <div class="col">
          <%= f.submit "登録する", class:"btn-flat-border" %>
      </div>
    </div>
  </div>
  <% end %> 
</div>

app/views/users/user_favorites/select.html.erb
<div class="main-visual">
  <div class="main-visual-content-rank">
      <div class="ransack_container">
        <h1>おすすめ歯磨き粉select</h1>
        <%= search_form_for(@q,url:users_select_user_favorite_path, method: :get,  local:true) do |f| %>
        <div class="container">
          <div class="row">
            <div class="col-2 mt-4">
              <%= f.label :tooth_paste_name, class:"font-color-white" %>
            </div>
            <div class="col-10 mt-2">
              <%= f.search_field :tooth_paste_name_cont, class:"ransack-textbox", placeholder:"Keyword" %>
            </div>
            <div class="col-2 mt-4">
              <%= f.label :price, class:"font-color-white" %>
            </div>
            <div class="col-9 mt-2">
              <%= f.number_field :price_gteq, class:"ransack-textbox-pricebox", placeholder:"price　more・・・" %>
              <%= f.number_field :price_lt, class:"ransack-textbox-pricebox", placeholder:"・・・less" %>
            </div>
            <div class="col-2 mt-4">
                <%= f.label :genre_genre_name, "genre", class:"font-color-white" %>
            </div>
            <div class="col-7 mt-2">
                <%= f.collection_select :genre_genre_name_eq, @genres, :genre_name, :genre_name,{prompt: ""}, {class: 'form-control ransack-textbox'} %>
                <%# genre_genre_name_eq → モデル名_カラム名_eq（ransackの書き方） %>  
            </div>
            <div class="col-10 mt-2">
            <%# <i class="fas fa-search" style="color:white;"></i> %>
              <%= f.submit "Search", class:"btn-flat-border" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  </div>
<% @pastes.each do |paste| %>
  <%= link_to(users_new_user_favorite_path(paste)) do %>
  <div class="my_page_box">
    <div class="container">
      <div class="row">
        <div class="col-3">
          <%= attachment_image_tag(paste, :image, size: '150x150') %>
        </div>
        <div class="col-9 row">
            <div class="col-11 offset-1">
              ジャンル：<%= paste.genre.genre_name %>
            </div>   
            <div class="col-11 offset-1">
             製品名：<%= paste.tooth_paste_name %>
            </div>
            <div class="col-11 offset-1">
             値段<%= paste.price %>円
            </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>
<% if @pastes.present? %>
  <%= paginate @pastes %>
<% end %>
 <%= link_to "マイページへ",users_user_favorite_path(@user_id), class:"font-color"	%>
 </div>

app/views/users/user_favorites/show.html.erb
<div class="main-visual">
  <div class="main-visual-content">
      <!-- pタグ（と文字）を追加 -->
      <p class="main-visual-text font-color-white">
          <%= current_user.name %>さんの<br>
          お気に入り一覧表示<br>
          編集<br>

      </p>
      </p>
  </div>
</div>
<div class="flash_message">
  <%= flash[:success] %>
</div>
<% @user_favorites.each do |favorite| %>
  <div class="my_page_box" style="height: 300px;">
    <div class="container">
      <div class="row">
        <div class="col-12">
            製品名:<%= favorite.paste.tooth_paste_name %>
        </div>
        <div class="col-3 row">
          <div class="col-12">
            <%= attachment_image_tag(favorite.paste, :image, size: '180x180') %>
          </div>
        </div>
        <div class="col-9 row">
          <div class="col-11 offset-1">
            ジャンル:<%= favorite.paste.genre.genre_name %>
          </div>
          <div class="col-11 offset-1">
              値段:<%= favorite.paste.price %>円
          </div>
          <div class="col-11 offset-1">
              コメント内容:<%= favorite.comment %>
          </div>
          <div class="col-11 offset-1">
              <%= link_to "Edit", edit_users_user_favorite_path(favorite), class:"btn-flat-border font-color" %>
              <%= link_to "Delete", users_user_favorite_path(favorite), method: :delete, data: { confirm: "削除しますか？" }, class:"btn-flat-border font-color" %>
          </div>
        </div>
      </div>
    </div>
 </div>
<% end %>
<%= paginate @user_favorites %>