config/routes.rb
Rails.application.routes.draw do
  get 'inquiries/new'
  get 'inquiries/create'
  root 'homes#top'

  resources :inquiries, only:[:new, :create]
  # get 'auth/:provider/callback', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
   devise_scope :user do
    # get '/users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    # # post '/users/sign_in' => 'users/sessions#create', as: 'user_session'
    # delete '/users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    # get '/users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    get '/users/passwords/edit' => 'users/registrations#edit', as: 'password_edit_registrations'
    patch '/users/passwords/update' => 'users/registrations#update'
    # post 'users/sign_up' => 'users/registrations#create', as: 'user_registration'
    # get '/users/' => 'users/passwords#edit', as: 'edit_user_password'
    # patch '/users/passwords' => 'users/passwords#update', as: 'user_password'
    get '/users/passwords/new' => 'users/passwords#new',as: 'user_forgot_password'
   end

  namespace :users do
    get 'users/select' => 'user_favorites#select', as: 'select_user_favorite'
    get 'users/new/:id' => 'user_favorites#new', as: 'new_user_favorite'
    resources :user_favorites, only:[:create, :show, :edit, :update, :destroy, :index]
    get 'users/genre_index' => 'pastes#genre_index', as: 'genre_index_paste'
    resources :pastes
  end
  # resources :pastes do
  #   resources :user_favorites
  # end


  devise_for :admins, skip: :all
    devise_scope :admin do
      get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
      post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
      delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session' 
    end
  authenticated :admin do
    namespace :admins do
      resources :genres, only:[:index, :create, :destroy, :edit, :update]
      get 'download',to:'pastes#download', as: 'download'
      resources :pastes, only:[:new, :create, :edit, :update, :destroy] do
         collection { post :import }
        # collection { post :csv_import }
      end
      resources :admin_recommends, only:[:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToothPaste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<header class="header">
  <nav>
    <ul class="nav-list">
      <h2 class="headline">ToothPasteMania</h2>
      <h5 class="flash_message_font" style="margin:30px 0 0 40px;">
        <%= flash[:inquiry_success] %>
      </h5>
      <% if admin_signed_in? %>
      <li class="nav-list-item">
        <%= link_to "歯磨き粉登録", new_admins_paste_path, class:"font-color" %>
      </li>
      <li class="nav-list-item">
        <%= link_to "おすすめ登録", new_admins_admin_recommend_path, class:"font-color" %>
      </li>
      <li class="nav-list-item">
        <%= link_to "おすすめ一覧", admins_admin_recommends_path, class:"font-color" %>
      </li>
      <li class="nav-list-item">
        <%= link_to "ジャンル登録", admins_genres_path, class:"font-color" %>
      </li>
      <li class="nav-list-item">
        <%= link_to "ログアウト", destroy_admin_session_path,method: :delete, class:"font-color" %>
      </li>
    <% else %>
    <% if user_signed_in? %>
        <li class="user_name">
          ようこそ <%= current_user.name %>さん
        </li>
        <li class="nav-list-item">
          <%= link_to "このサイトについて", root_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ランキング", users_user_favorites_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "マイページ", users_user_favorite_path(current_user.id), class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "おすすめ", users_select_user_favorite_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "お問合せ", inquiries_new_path, class:"font-color" %>
        </li>
      <% else %>
        <li class="nav-list-item">
          <%= link_to "このサイトについて", root_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ランキング", users_pastes_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "新規登録", new_user_registration_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ログイン", new_user_session_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "お問合せ", inquiries_new_path, class:"font-color" %>
        </li>
        <li class="nav-list-item">
          <%= link_to '管理者の方はこちら', new_admin_session_path, class:"font-color"  %>
        </li>
      <% end %>
      <% end %>
    </ul>
  </nav>
</header>
  <%= yield %>
  <footer class="footer">
    <p class="footer-text">© toothpastemania.</p>
  </footer>
  </body>
</html>